name: pytest with github actions

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Set up Python 3.12
              uses: actions/setup-python@v2
              with:
                python-version: "3.12"
            
            - name: Install rye
              run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
            
            - name: activate rye
              run: |
                source $HOME/.rye/env
                rye sync
                source .venv/bin/activate
                rye run pytest tests/test_main.py
            
            - name: Setup tmate session for debugging
              if: failure()
              uses: mxschmitt/action-tmate@v3
